name: Test

on:
  push:
  pull_request:

jobs:

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    strategy:
      matrix:
        platform:
          - ubuntu
          - macOS
          - windows
        go:
          - 19
          - 20
          - 21
    name: '${{ matrix.platform }} | 1.${{ matrix.go }}.x'
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.${{ matrix.go }}.x

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test  -v ./...
